name: CI Build & Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    name: CI Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Vault
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install vault jq -y

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Pack build artifacts
        run: |
          npm pack
          echo "PKG_NAME=$(jq -r ".name" package.json)-$(jq -r ".version" package.json).tgz" >> $GITHUB_ENV

      - name: Share build artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.PKG_NAME }}
          if-no-files-found: error
