name: Wiki Update
on:
  push:
    branches:
      - master
    paths:
      - 'wiki/*'
jobs:
  wiki-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload Documentation to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_MAIL: ${{ secrets.GH_EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
          EXCLUDED_FILES: "a/ b.md"
